name: environment test
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test-environment:
    runs-on: ubuntu-20.04
    environment:
      name: test
    env:
      AWS_DEFAULT_REGION: us-west-2
      SECRETS_CONTEXT: ${{ toJson(secrets) }}
    steps:
      - name: Convert to environment variables
        run: |
          while read -rd $'' line
          do
            echo "$line" >> $GITHUB_ENV
          done < <(jq -r <<<"$SECRETS_CONTEXT" \
            'to_entries|map("\(.key)=\(.value)\u0000")[]')
      - name: Printenv
        run: |
          printenv

