name: environment test
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test-environment:
    runs-on: ubuntu-20.04
    env:
      AWS_DEFAULT_REGION: us-west-2
    steps:
      - name: Convert to environment variables
        uses: sergeysova/jq-action@v2
        with: 
          cmd: |
            for s in $(echo $values | jq -r "to_entries|map(\"\(.key)=\(.value|tostring)\")|.[]" ); do
              echo $s >> $GITHUB_ENV
            done
      - name: Printenv
        run: |
          printenv

