name: environment test
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test-environment:
    runs-on: ubuntu-20.04
    environment:
      name: test
    env:
      AWS_DEFAULT_REGION: us-west-2
      SECRETS_CONTEXT: ${{ toJson(secrets) }}
    steps:
      - name: Convert to environment variables
        run: |
          for s in $(echo $SECRETS_CONTEXT | jq -r "to_entries|map(\"\(.key)=\(.value|tostring)\")|.[]" ); do
            echo $s >> $GITHUB_ENV
          done
      - name: Printenv
        run: |
          printenv

